// export const topics = [
//   "Academic Stress 📚",
//   "Exam Anxiety 😰",
//   "Procrastination 🕒",
//   "Time Management ⏳",
//   "Burnout 🔥",
//   "Social Pressure 🤝",
//   "Loneliness 😔",
//   "Roommate Issues 🏠",
//   "Career Uncertainty 💼",
//   "Financial Stress 💸",
//   "Homesickness 🏡",
//   "Imposter Syndrome 🥸",
//   "Mental Health 🧠",
//   "Study Tips ✏️",
//   "Group Projects 👥",
//   "Part-Time Jobs 🕑",
//   "Overcommitment 📅",
//   "Sleep Deprivation 🌙",
//   "Motivation 💪",
//   "Campus Life 🎓",
// ];

export const topics =[
  "Anxiety",
  "Depression",
  "Confidence",
  "Relationships" ,
  "Stress",
  "Trauma",
  "Grief",
  "Loneliness",
  "Burnout",
  "Addiction",
  "Sleep",
  "Anger",
  "Identity",
  "Motivation",
  "Focus",
  "Fear",
  "Self-Harm",
  "Social Pressure",
  "None"
]
