// export const topics = [
//   { topic: "Academic Stress", icon: "book-outline" },
//   { topic: "Exam Anxiety", icon: "alert-circle-outline" },
//   { topic: "Procrastination", icon: "time-outline" },
//   { topic: "Time Management", icon: "timer-outline" },
//   { topic: "Burnout", icon: "flame-outline" },
//   { topic: "Social Pressure", icon: "people-outline" },
//   { topic: "Loneliness", icon: "person-remove-outline" },
//   { topic: "Roommate Issues", icon: "home-outline" },
//   { topic: "Career Uncertainty", icon: "briefcase-outline" },
//   { topic: "Financial Stress", icon: "cash-outline" },
//   { topic: "Homesickness", icon: "home-outline" },
//   { topic: "Imposter Syndrome", icon: "help-circle-outline" },
//   { topic: "Mental Health", icon: "heart-outline" },
//   { topic: "Study Tips", icon: "pencil-outline" },
//   { topic: "Group Projects", icon: "people-outline" },
//   { topic: "Part-Time Jobs", icon: "business-outline" },
//   { topic: "Overcommitment", icon: "calendar-outline" },
//   { topic: "Sleep Deprivation", icon: "moon-outline" },
//   { topic: "Motivation", icon: "thumbs-up-outline" },
//   { topic: "Campus Life", icon: "school-outline" },
// ];



export const topics = [ 
  "Anxiety",
  "Depression",
  "Confidence",
  "Relationships",
  "Stress",
  "Trauma",
  "Grief",
  "Loneliness",
  "Burnout",
  "Addiction",
  "Sleep",
  "Anger",
  "Identity",
  "Motivation",
  "Focus",
  "Fear",
  "Self-Harm",
  "Social Pressure",
  "General",
];